create DATABASE if not EXISTS jwt_auth_db;
use jwt_auth_db;
show DATABASES;
CREATE TABLE IF NOT EXISTS 
Users (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
email VARCHAR (100) UNIQUE NOT NULL,
pass_hash VARCHAR (255) NOT NULL,
name VARCHAR (100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
SHOW TABLES;
SELECT * FROM USERS;
DESCRIBE USERS;


CREATE TABLE IF NOT EXISTS 
UserSessions (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
user_id INT UNSIGNED NOT NULL,
ip_address VARCHAR (45),
user_agent TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);

SHOW TABLES;
SELECT * FROM UserSessions;
DESCRIBE UserSessions;