USE cafe_artesanal;
DESCRIBE Roles;
INSERT INTO Roles VALUES
	(NULL, "ADMIM", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(NULL, "Seller", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(NULL, "Customer", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	

SELECT * FROM Roles;